// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onSpasticityLevelChange();
void onDurationMinutesChange();
void onOnOffChange();
void onSpeedChange();

float spasticityLevel;
int durationMinutes;
int onOff;
int remainingSeconds;
CloudVelocity speed;

void initProperties(){

  ArduinoCloud.addProperty(spasticityLevel, READWRITE, ON_CHANGE, onSpasticityLevelChange);
  ArduinoCloud.addProperty(durationMinutes, READWRITE, ON_CHANGE, onDurationMinutesChange);
  ArduinoCloud.addProperty(onOff, READWRITE, ON_CHANGE, onOnOffChange);
  ArduinoCloud.addProperty(remainingSeconds, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(speed, READWRITE, ON_CHANGE, onSpeedChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
